In [5]:
#METROPOLIS RANDOM SPIN SELECTION

import numpy as np
import math
import itertools
import random 
import time


time_start = time.clock()
L=10
N=L**2
k=0.45
mc=100
M=1000
Mtherm=10

s=np.random.choice([1, -1], size=(L, L))

def neighbors(s, L, x, y):
    left   = (x, y - 1)
    right  = (x, (y + 1) % L)
    top    = (x - 1, y)
    bottom = ((x + 1) % L, y)

    return [s[left[0], left[1]],
            s[right[0], right[1]],
            s[top[0], top[1]],
            s[bottom[0], bottom[1]]]



for q in range(Mtherm):
    i=np.random.randint(0, L)
    j=np.random.randint(0, L)
    ib=s[i][j]*np.sum(neighbors(s,L,i,j))
    if np.random.uniform()< np.exp(-2*k*ib):
        s[i][j]=-s[i][j]



rm1=np.float(abs(sum(s[p][q] for p in range(L) for q in range(L))))/N
c=0
rm2=0
rm=0
for u in range(M):
    for w in range(mc):          #we measure every N updates of the spins
        i=np.random.randint(0, L)
        j=np.random.randint(0, L)
        ib=s[i][j]*np.sum(neighbors(s,L,i,j))
        if ib<=0:
            s[i][j]=-s[i][j]
        if ib>0 and np.random.uniform()< np.exp(-2*k*ib):
            s[i][j]=-s[i][j] 
            
    rm0=np.float(abs(sum(s[p][q] for p in range(L) for q in range(L))))/N
    rm=rm+rm0
    rm2=rm2+rm0**2
    c=c+rm0*rm1
    rm1=rm0


mag=np.float(rm)/M
rm2=np.float(rm2)/M-mag**2
c=np.float(float(c)/M-mag**2)/rm2
tau=np.float(c)/(1-c)
errorsintau=np.sqrt(float(rm2)/M)
error=np.sqrt(float(rm2)*(2*tau+1)/M)

print(mag,tau,errorsintau,error)


time_elapsed = (time.clock() - time_start)
print(time_elapsed)  


(0.8050800000000002, 10.296970359989194, 0.0059600497984498395, 0.027695922855937447)
10.1940106


In [57]:
#SEQUENTIAL UPDATING


time_start = time.clock()
L=10
N=L**2
k=0.45
mc=100
M=10000
Mtherm=100

s=np.random.choice([1, -1], size=(L, L))

def neighbors(s, L, x, y):
    left   = (x, y - 1)
    right  = (x, (y + 1) % L)
    top    = (x - 1, y)
    bottom = ((x + 1) % L, y)

    return [s[left[0], left[1]],
            s[right[0], right[1]],
            s[top[0], top[1]],
            s[bottom[0], bottom[1]]]



for q in range(Mtherm):
    i=np.random.randint(0, L)
    j=np.random.randint(0, L)
    ib=s[i][j]*np.sum(neighbors(s,L,i,j))
    if np.random.uniform()< np.exp(-2*k*ib):
        s[i][j]=-s[i][j]


m=[]
rm1=np.float(abs(sum(s[p][q] for p in range(L) for q in range(L))))/N
c=0
rm2=0
rm=0
for u in range(M):
    for i in range(L):
        for j in range(L):
            ib=s[i][j]*np.sum(neighbors(s,L,i,j))
            if ib<=0:
                s[i][j]=-s[i][j]
            if ib>0 and np.random.uniform()< np.exp(-2*k*ib):
                s[i][j]=-s[i][j] 
            
    rm0=np.float(abs(sum(s[p][q] for p in range(L) for q in range(L))))/N
    rm=rm+rm0
    rm2=rm2+rm0**2
    c=c+rm0*rm1
    rm1=rm0


mag=np.float(rm)/M
rm2=np.float(rm2)/M-mag**2
c=np.float(float(c)/M-mag**2)/rm2
tau=np.float(c)/(1-c)
errorsintau=np.sqrt(float(rm2)/M)
error=np.sqrt(float(rm2)*(2*tau+1)/M)

print(mag,tau,errorsintau,error)







time_elapsed = (time.clock() - time_start)
print(time_elapsed)  



(0.7985019999999766, 3.464919409023324, 0.0017389294406631045, 0.004896819999825499)
87.4415386


In [58]:
#CHESS !!
time_start = time.clock()
L=10
N=L**2
k=0.45
mc=100
M=10000
Mtherm=100

s=np.random.choice([1, -1], size=(L, L))

def neighbors(s, L, x, y):
    left   = (x, y - 1)
    right  = (x, (y + 1) % L)
    top    = (x - 1, y)
    bottom = ((x + 1) % L, y)

    return [s[left[0], left[1]],
            s[right[0], right[1]],
            s[top[0], top[1]],
            s[bottom[0], bottom[1]]]

def metropolis(s,L,x,y):
    ib=s[x][y]*np.sum(neighbors(s,L,x,y))
    if ib<=0:
        s[x][y]=-s[x][y]
    if ib>0 and np.random.uniform()< np.exp(-2*k*ib):
        s[x][y]=-s[x][y]
    return s


for q in range(Mtherm):
    i=np.random.randint(0, L)
    j=np.random.randint(0, L)
    ib=s[i][j]*np.sum(neighbors(s,L,i,j))
    if np.random.uniform()< np.exp(-2*k*ib):
        s[i][j]=-s[i][j]


        
        
m=[]
rm1=np.float(abs(sum(s[p][q] for p in range(L) for q in range(L))))/N
c=0
rm2=0
for u in range(M):
    for i in range(0,L,2):
        for j in range(0,L,2):
            metropolis(s,L,i,j)
    for i in range(1,L,2):
        for j in range(1,L,2):
            metropolis(s,L,i,j)
    for i in range(0,L,2):
        for j in range(1,L,2):
            metropolis(s,L,i,j)
    for i in range(1,L,2):
        for j in range(0,L,2):
            metropolis(s,L,i,j)
            
    rm0=np.abs(sum(s[p][q] for p in range(L) for q in range(L)))/N
    rm2=rm2+rm0**2
    c=c+rm0*rm1
    rm1=rm0

    m.append(np.abs(float(sum(s[p][q] for p in range(L) for q in range(L)))/N))

mag=np.float(sum(m))/M
c=(np.float(c)/M-mag**2)/rm2
tau=np.float(c)/(1-c)
sigma2=np.float(sum(m*2))/M-mag**2

print(mag,tau,np.sqrt(float(sigma2)/M),np.sqrt(float(sigma2)/M*(2*tau+1)))







time_elapsed = (time.clock() - time_start)
print(time_elapsed)  
















(0.779475999999979, -0.004345657544881597, 0.00975381548638243, 0.009711336242971678)
88.6064344


In [59]:
#chess un poco más pro

time_start = time.clock()
L=10
N=L**2
k=0.45
mc=100
M=10000
Mtherm=100

s=np.random.choice([1, -1], size=(L, L))

def neighbors(s, L, x, y):
    left   = (x, y - 1)
    right  = (x, (y + 1) % L)
    top    = (x - 1, y)
    bottom = ((x + 1) % L, y)

    return [s[left[0], left[1]],
            s[right[0], right[1]],
            s[top[0], top[1]],
            s[bottom[0], bottom[1]]]

def metropolis(s,L,x,y):
    ib=s[x][y]*np.sum(neighbors(s,L,x,y))
    if ib<=0:
        s[x][y]=-s[x][y]
    if ib>0 and np.random.uniform()< np.exp(-2*k*ib):
        s[x][y]=-s[x][y]
    return s


for q in range(Mtherm):
    i=np.random.randint(0, L)
    j=np.random.randint(0, L)
    ib=s[i][j]*np.sum(neighbors(s,L,i,j))
    if np.random.uniform()< np.exp(-2*k*ib):
        s[i][j]=-s[i][j]


def checkboard(s,L):
    for i in range(0,L,2):
        for j in range(0,L,2):
            metropolis(s,L,i,j)
    for i in range(1,L,2):
        for j in range(1,L,2):
            metropolis(s,L,i,j)
    for i in range(0,L,2):
        for j in range(1,L,2):
            metropolis(s,L,i,j)
    for i in range(1,L,2):
        for j in range(0,L,2):
            metropolis(s,L,i,j)
    return(s)
    
        
m=[]
rm1=np.float(abs(sum(s[p][q] for p in range(L) for q in range(L))))/N
c=0
rm2=0
rm=0
for u in range(M):
    checkboard(s,L)
    rm0=np.float(abs(sum(s[p][q] for p in range(L) for q in range(L))))/N
    rm=rm+rm0
    rm2=rm2+rm0**2
    c=c+rm0*rm1
    rm1=rm0


mag=np.float(rm)/M
rm2=np.float(rm2)/M-mag**2
c=np.float(float(c)/M-mag**2)/rm2
tau=np.float(c)/(1-c)
errorsintau=np.sqrt(float(rm2)/M)
error=np.sqrt(float(rm2)*(2*tau+1)/M)

print(mag,tau,errorsintau,error)







time_elapsed = (time.clock() - time_start)
print(time_elapsed)  







(0.7926859999999805, 6.041832783764103, 0.0018285290646869441, 0.0066140364681099165)
85.7881885


In [47]:

L=3
s=np.random.choice([1, -1], size=(L, L))
print(s)


def metropolis(s,L,x,y):
    ib=s[x][y]*np.sum(neighbors(s,L,x,y))
    if ib<=0:
        s[x][y]=-s[x][y]
    if ib>0 and np.random.uniform()< np.exp(-2*k*ib):
        s[x][y]=-s[x][y]
    return s


def checkboard(s,L):
    for i in range(0,L,2):
        for j in range(0,L,2):
            metropolis(s,L,i,j)
    for i in range(1,L,2):
        for j in range(1,L,2):
            metropolis(s,L,i,j)
    for i in range(0,L,2):
        for j in range(1,L,2):
            metropolis(s,L,i,j)
    for i in range(1,L,2):
        for j in range(0,L,2):
            metropolis(s,L,i,j)
    return(s)

print(s,checkboard(s,L))


[[ 1 -1 -1]
 [ 1  1 -1]
 [ 1 -1  1]]
(array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]]), array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]]))


In [34]:
L=3
s=np.random.choice([1, -1], size=(L, L))
print(s)
def metropolis(s,L,x,y):
    ib=s[x][y]*np.sum(neighbors(s,L,x,y))
    if ib<=0:
        s[x][y]=-s[x][y]
    if ib>0 and np.random.uniform()< np.exp(-2*k*ib):
        s[x][y]=-s[x][y]
    return s

print(metropolis(s,L,1,1))

[[ 1 -1 -1]
 [ 1  1  1]
 [-1 -1  1]]
[[ 1 -1 -1]
 [ 1 -1  1]
 [-1 -1  1]]
